lsi: false
safe: true
source: /
title: Oportis page
logo: oportis-logo.png
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
remote_theme: pages-themes/minimal@v0.2.0
show_downloads: false
plugins:
- jekyll-remote-theme
github:
  is_project_page: false